title: ミニかわロボ公式
description: 手のひらサイズの格闘ロボット競技『ミニかわロボ』の公式製作ガイド＆ルール
url: "https://sin1n24.github.io"
baseurl: "/MiniKawaRobo"

# ---------------------------------------------
# ここから下が、エラーを直すための重要な設定です
# ---------------------------------------------

# GitHubのリポジトリから直接テーマを読み込む設定
remote_theme: just-the-docs/just-the-docs

# 外部テーマを読み込むためのプラグインを有効化
plugins:
  - jekyll-remote-theme
