title: ミニかわロボ公式リソース集
description: 手のひらサイズの格闘ロボット競技『ミニかわロボ』の公式製作ガイド＆ルール
theme: just-the-docs # ベースとなるテーマ
url: "https://sin1n24.github.io"
baseurl: "/MiniKawaRobo"

# ランディングページ用のカスタマイズ設定
color_scheme: dark # モダンな印象を与えるためダークモード基調にする（好みで外してもOK）
